language: node_js
services:
  - mongodb
node_js:
  - "4.2.2"
  - "5.0.0"
branches:
  only:
    - master
sudo: false
script: "npm test"
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  region: us-east-1
  app: tessellate
  env: tessellate-stg
  bucket_name: $BUCKET
