language: node_js
services:
  - mongodb
node_js:
  - "5.9.0"
branches:
  only:
    - master
sudo: false
script: "npm run build && npm test"
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU
  app: tessellate-stg
